apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    # This is where the application container would go, for example
    # - name: nginx
    #   image: nginx
    # This is the ambassador container
    - name: test-pod
      image: busybox:1.28.4
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
      resources:
        limits:
          cpu: 100m
          memory: 3Gi
        requests:
          cpu: 100m
          memory: 1Gi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
  volumes:
    - name: config-volume
      configMap:
        name: redis-configmap