apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: atlas
spec:
  serviceName: "redis"
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: 100m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000